### PR TITLE
libbyspalding-here to the site

### PR DESCRIPTION
**Pull request by libbyspalding**

### CODE REVIEW

**Comment by acoravos** [comment]
Ah, there's some conflicts with the master branch. You'll get to learn how to manage conflicts :)

Checkout the master branch `git checkout master` and then pull down the new changes (`git pull origin master`). Then switch over to your feature branch (`git checkout libbys/add-photo-to-site`). Then you'll want to merge in master by doing `git merge master`.

It will tell you that you have conflicts, which is ok! Then go to your _config.yml file and see row 105. You'll see >>>>>>>> and then HEAD and then >>>>>> and Master. A couple other members had added their information since you had originally pulled the codebase. Delete all the ">>>>>" and HEAD and MASTER, and keep the profiles for everyone.

Then you'll add these changes `git add .` and then make a commit `git commit -m "merge master updates"`. Then push up those changes, `git push origin libbys/add-photo-to-site`. Then you'll see that there aren't any conflicts on this branch anymore.

We can also do this together at CODE next week if you'd like :) But think you might be able to take a cut at it! Merge conflicts are no fun. But it happens when lots of people are editing the same part of the codebase.

Also! You can talk with @alisonyshin. She had to go through the same thing. #parallelprogramming

**Comment by acoravos** [comment]
@andrep would it be possible to add the `_site/index.html` file to gitignore? You correctly saw this issue coming :)

The _config file will be fixed by Libby, but the site file will be auto-regenerated.

**Comment by alisonyshin** [comment]
@libbyspalding Yep, I definitely had the same issue. Let's talk!

@acoravos @andrep I understand how to work around this problem, but what exactly is gitignore and how is it going to solve the issue? Thanks!

**Comment by bluxenberg** [comment]
Can you all unsubscribe me from this?

**Comment by bluxenberg** [comment]
Hey Andrea, can you unsubscribe me from this thread?

Ben

**Comment by acoravos** [comment]
@bluxenberg I believe this has to do with your email settings -- there is no way to unsubscribe you from my end. Try these two approaches

(1) Unwatch the repository. Details here: https://help.github.com/articles/unwatching-repositories/

(2) Go in to your settings and see when GitHub will email you

**Comment by andrep** [comment]
@acoravos The entire _site/ directory should be ignored (no need to add every file in the directory to .gitignore, adding the directory will take care of it).

@alisonyshin the .gitignore file contains a list of files that should be ignored if you make changes to them. In this case, the _site directory is modified when you run the "jekyll serve" command, since jekyll uses the _site directory as a staging area. So we don't want any changes that are made to the _site directory to be committed 

@acoravos In fact, we should get rid of the _site directory from the repository altogether since it's auto-generated, I'll open a PR for that.

**Pull request merged**
