### PR TITLE
dp/add-member

### PR DESCRIPTION
**Pull request by dpeng-dev**

### CODE REVIEW

**Comment by acoravos** [comment]
Nice work! :shipit:

**Comment by acoravos** [comment]
Wahoo deployed. 

Check out: codehbsclub.com

Cc: @abhagi @ygoncho @benjamincohen1989

**Comment by acoravos** [comment]
Curious, any idea why you don't come up as one of the contributors now? https://github.com/codehbs/codehbs-official-homepage/graphs/contributors

Is it because I merged in the request? Or does it take a few hours to update that graphic. Have you confirmed your membership to our GitHub org?

**Comment by dpeng-dev** [comment]
Thanks Andrea. Not sure about not showing up as a contributor. I just
accepted your Github membership so maybe it will update soon.

Btw, I followed your instructions (very helpful) but got stuck on README on
git-workflow/README.md until I figured out that I needed to commit my
branch. Could be worth updating the step on that workflow instruction to
include git commit after merge in case others also get stuck.

Daniel

**Comment by acoravos** [comment]
Oh brilliant. @abe732 is taking another cut at the README. Think he caught that one, too. 

Thx for the feedback.

**Pull request merged**
