### PR TITLE
add sasha pang to site

### PR DESCRIPTION
**Pull request by sashapang**

### CODE REVIEW

**Comment by acoravos** [comment]
Looks good! But I only see the changes you made to the `_config` file and I don't see your photo in the commit. Could you add that and I'll merge it in?

**Comment by acoravos** [comment]
Looks good!! :shipit:

**Comment by acoravos** [comment]
You are live! Check out codehbsclub.com.

**Comment by sashapang** [comment]
Yaaaaay thanks!!

**Pull request merged**
