### PR TITLE
add tatiana cooke to site

### PR DESCRIPTION
**Pull request by tatstuff**
Attempt #2!

### CODE REVIEW

**Comment by acoravos** [comment]
Yay! Only see your `_config` file though and not your jpg / photo. See "files changed" only has 1. 

Sometimes doing `git add .` will add the photo to the commit. Lots of people didn't have the photo added because sometimes git is weird when adding a new file (vs. changing an existing file).

**Comment by tatstuff** [comment]
just fixed, I think

**Comment by acoravos** [comment]
Yay -- You're live on www.codehbsclub.com!

**Comment by tatstuff** [comment]
So exciting!!!! Thank you ☺

**Pull request merged**
