### PR TITLE
add Alison to site

### PR DESCRIPTION
**Pull request by alisonyshin**

### CODE REVIEW

**Comment by acoravos** [comment]
Sweet! This pull request only has your photo file (see that it says only 1 file changed), but not the change to the `_config.yml` file. Maybe go back and try `git add .` and then `git commit -m "your message"` and it will probably grab your changes from the config file.

**Comment by acoravos** [comment]
@andrep the last two pull requests have had conflicts with the `_site/index.html` files. Do you think this has anything to do with the gitignores?

**Comment by acoravos** [comment]
Ah, I know why. It's because some people have made updates since pulling down master. @andrep 

@alisonyshin, let's do one last thing. Checkout the master branch `git checkout master` and then pull down the new changes (`git pull origin master`). Then switch over to your feature branch (`git checkout as/add-shin-photo-and-social-links`). Then you'll want to merge in master by doing `git merge master`. 

It will tell you that you have conflicts, which is ok! Then go to your `_config.yml` file and see row 104. You'll see >>>>>>>> and then HEAD and then >>>>>> and Master. Christina made some changes (and perhaps a few others). Delete all the ">>>>>" and HEAD and MASTER, and keep the profiles for everyone. 

Then you'll add these changes `git add .` and then make a commit `git commit -m "merge master updates"`. Then push up those changes, `git push origin as/add-shin-photo-and-social-links`. Then you'll see that there aren't any conflicts on this branch anymore.

We can also do this together on Tuesday if you'd like :) But think you might be able to take a cut at it! Merge conflicts are no fun. But it happens when lots of people are editing the same part of the codebase.

**Comment by andrep** [comment]
@acoravos The .gitignore changes should prevent these changes happening in the future; the conflicts in these pull requests are because people are seeing changes to the _site directory, before changes to the .gitignore, and unintentionally committing them. (That's the main reason I wanted to commit then.)

@alisonyshin Good luck with the merge conflict changes, let us know if you'd like any help at all.

**Comment by alisonyshin** [comment]
Thanks for all your help, @acoravos @andrep !
I think it should be good now!

**Comment by acoravos** [comment]
Yay! You are live. Check out www.codehbsclub.com.

**Pull request merged**
