### PR TITLE
adding ryan jones to members list

### PR DESCRIPTION
**Pull request by jones2718281**

### CODE REVIEW

**Comment by acoravos** [comment]
@jones2718281 -- this pull request has conflicts. I noticed a few two things. First, the group photo at the bottom is now missing (see www.codehbsclub.com). Also, there have been updates to master in the past few days and a couple other members have been added now. 

A way to update this would be to switch back to the master branch (`git checkout master`), and then pull down the master (`git pull origin master`). Then you can switch over to your branch (`rj/add-ryan-memberslist`) and merge in the new changes from master (`git merge master`). You might face merge conflicts when this happens. If you do, check out your editor and I suspect it's because the "group photo" at the bottom is missing.

I'd then re-run `jekyll serve` locally to see if works and push up the updates. I believe the updates will get automatically added to your pull request.

A

**Comment by acoravos** [comment]
You're one of our early adopters! You got this out even before many members of our board, so big bonus points 👍 👍 👍

**Comment by jones2718281** [comment]
@acoravos Bah! Gets a bit messy when lots of people edit between the fork and the commit :-)

Fix suggested above only works for unforked pull requests.   In case anyone else runs into the same problem and wants to solve it without re-forking, put a solution below. 

```

# Add remote
rjones$ git remote add upstream https://github.com/codehbs/codehbs-official-homepage.git
rjones$ git remote -v
origin  https://github.com/jones2718281/codehbs-official-homepage.git (fetch)
origin  https://github.com/jones2718281/codehbs-official-homepage.git (push)
upstream    https://github.com/codehbs/codehbs-official-homepage.git (fetch)
upstream    https://github.com/codehbs/codehbs-official-homepage.git (push)

# Sync to the base repo
rjones$ git fetch upstream
rjones$ git checkout master
rjones$ git rebase upstream/master
rjones$ git push origin master

# Fix the conflicts
rjones$ git checkout rj/add-ryan-memberslist
rjones$ git merge master
rjones$ git mergetool 
rjones$ git commit -m "Syncing RJ's fork to upstream & merging commits"

# Modified from http://stackoverflow.com/questions/7244321/how-do-i-update-a-github-forked-repository

```

**Comment by acoravos** [comment]
Ooof. Nice work-around. Thanks for writing that up! I'm sure this will happen again given the number of forks that are going to occur.

**Comment by acoravos** [comment]
Deployed! Check out: www.codehbsclub.com.

:shipit:

**Comment by jones2718281** [comment]
Woohoo!

fyi- another option to escape forking if you need tiered write permissions on a project is to give admins write access to master, but only rest of the dev team write permissions to push to specific branches (ie sandbox/\* or feature/\* or {username}/\*  ).  Not sure if github has an easy way to do that though.. seems like they love forks.

**Comment by acoravos** [comment]
@jones2718281 -- I like your idea 100x more than forking. I'm sure that exists as a feature set for GitHub, but I'd have to look into it more this weekend.

We're going to do a walk through next Monday to have lots of people add their name to the site and that would be much cleaner than teaching people remotes and rebasing.

cc: @abhagi @ygoncho @abe732 @bansishah

**Comment by acoravos** [comment]
I figured out how to make "protected branches" in GitHub, and I've applied this setting to `master` and `gh-pages.`

If you're curious: https://help.github.com/articles/about-protected-branches/

This means I can remove the forking section from the README, and this will make the walk through next week MUCH easier.

**Pull request merged**
